minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - workerd

overrides:
  undici@>=7.0.0 <7.18.2: ">=7.18.2"

# Work around https://github.com/sveltia/sveltia-cms-auth/issues/17
packages:
  - .

auditConfig:
  ignoreGhsas:
    # https://github.com/advisories/GHSA-3ppc-4f35-3m26
    - GHSA-3ppc-4f35-3m26
