allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
  workerd: false

engineStrict: true

minimumReleaseAge: 1440

# Work around https://github.com/sveltia/sveltia-cms-auth/issues/17
packages:
  - .

overrides:
  # https://github.com/advisories/GHSA-rgw5-rvv9-x895
  brace-expansion@>=4.0.0 <5.0.8: ^5.0.8
  # https://github.com/advisories/GHSA-4cwx-7wf7-3272 and 5 others
  undici@>=7.0.0 <7.29.0: ^7.29.0
