minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - workerd

overrides:
  undici@>=7.0.0 <7.18.2: ">=7.18.2"

# Work around https://github.com/sveltia/sveltia-cms-auth/issues/17
packages:
  - .

auditConfig:
  ignoreCves:
    # ESLint https://github.com/advisories/GHSA-p5wg-g6qr-c7cg
    - CVE-2025-50537
